name: "ci-cd pipeline"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # Install Vite globally
      - name: Install Vite
        run: npm install -g create-vite@latest

      # Create Vite app and install dependencies using pnpm
      - name: Create Vite app and Install dependencies
        run: |
          create-vite my-vite-app --template vue
          cd my-vite-app
          npm install -g pnpm
          pnpm install

      # Run tests (if applicable)
      - name: Run tests
        run: pnpm test

      # Build the Vite app
      - name: Build Vite app
        run: pnpm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './my-vite-app/dist'  # Adjust the build directory based on your Vite app configuration
          comment-on-commit: true
